site_name: Mikapod Soil (Raspberry Pi)
nav:
    - Home: index.md
    - Architecture: architecture.md
    - Hardware: parts.md
    - Installation: installation.md
    - Services:
        - Nameserver Service: services/nameserver.md
        - Storage Service: services/storage.md
        - Instrumentats Service: services/instrumentation.md
        - Logging Service: services/logging.md
        - Remote Service: services/remote.md
theme: readthedocs
